const columns = [
    { name: "USERNAME", uid: "username" },
    { name: "EMAIL", uid: "email" },
    { name: "PHONENUMBER", uid: "phoneNumber" },
    { name: "ADDRESS", uid: "address" },
    { name: "ACTIONS", uid: "actions" },
];
const sampleCustomer = [
    {
        username: 'alice_jones',
        password: 'pass1234',
        email: 'alice.jones@example.com',
        role: 'user',
        fullName: 'Alice Jones',
        phoneNumber: '5551234567',
        address: '789 Oak St, Villagetown',
        isDriver: false,
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamC',
    },
    {
        username: 'bob_smith',
        password: 'bobpass',
        email: 'bob.smith@example.com',
        role: 'admin',
        fullName: 'Bob Smith',
        phoneNumber: '5559876543',
        address: '101 Pine St, Hamletsville',
        isDriver: true,
        driverInfo: {
            licenseNumber: 'DL654321',
            vehicleType: 'Truck',
        },
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamA',
    },
    {
        username: 'carol_davis',
        password: 'carolpass',
        email: 'carol.davis@example.com',
        role: 'user',
        fullName: 'Carol Davis',
        phoneNumber: '5558765432',
        address: '456 Birch St, Countryside',
        isDriver: false,
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamB',
    },
    {
        username: 'david_wilson',
        password: 'davidpass',
        email: 'david.wilson@example.com',
        role: 'user',
        fullName: 'David Wilson',
        phoneNumber: '5552345678',
        address: '789 Maple St, Suburbia',
        isDriver: true,
        driverInfo: {
            licenseNumber: 'DL987654',
            vehicleType: 'Motorcycle',
        },
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamC',
    },
    {
        username: 'elena_miller',
        password: 'elenapass',
        email: 'elena.miller@example.com',
        role: 'driver',
        fullName: 'Elena Miller',
        phoneNumber: '5553456789',
        address: '123 Cedar St, Riverside',
        isDriver: true,
        driverInfo: {
            licenseNumber: 'DL321987',
            vehicleType: 'Van',
        },
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamA',
    },
    {
        username: 'frank_jenkins',
        password: 'frankpass',
        email: 'frank.jenkins@example.com',
        role: 'admin',
        fullName: 'Frank Jenkins',
        phoneNumber: '5554567890',
        address: '456 Elm St, Mountainside',
        isDriver: false,
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamB',
    },
    {
        username: 'grace_thompson',
        password: 'gracepass',
        email: 'grace.thompson@example.com',
        role: 'user',
        fullName: 'Grace Thompson',
        phoneNumber: '5555678901',
        address: '101 Spruce St, Lakeside',
        isDriver: true,
        driverInfo: {
            licenseNumber: 'DL123789',
            vehicleType: 'SUV',
        },
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamC',
    },
    {
        username: 'henry_adams',
        password: 'henrypass',
        email: 'henry.adams@example.com',
        role: 'user',
        fullName: 'Henry Adams',
        phoneNumber: '5556789012',
        address: '789 Walnut St, Coastalville',
        isDriver: false,
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamA',
    },
    {
        username: 'isabel_cooper',
        password: 'isabelpass',
        email: 'isabel.cooper@example.com',
        role: 'driver',
        fullName: 'Isabel Cooper',
        phoneNumber: '5557890123',
        address: '456 Pine St, Farmland',
        isDriver: true,
        driverInfo: {
            licenseNumber: 'DL456123',
            vehicleType: 'Bicycle',
        },
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamB',
    },
    {
        username: 'jack_rogers',
        password: 'jackpass',
        email: 'jack.rogers@example.com',
        role: 'user',
        fullName: 'Jack Rogers',
        phoneNumber: '5558901234',
        address: '101 Cedar St, Valleyville',
        isDriver: true,
        driverInfo: {
            licenseNumber: 'DL789456',
            vehicleType: 'Pickup Truck',
        },
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        team: 'TeamC',
    },
];

// Log the sample users

export { columns, sampleCustomer };
